WeShop.WeXin/Controllers/ProDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeShop.IService;
using WeShop.WeXin.Models;

namespace WeShop.WeXin.Controllers
{
    public class ProDetailController : Controller
    {
        public IProductService ProductService { get; set; }

        public IPublishService PublishService { get; set; }
        public IStockService StockService { get; set; }
        public ITagService TagService { get; set; }

        public ActionResult Index(string prodetailCode)
        {
            PublishViewModel publishViewModel = new PublishViewModel();

            publishViewModel.Products = ProductService.GetEntities(n => n.Code == prodetailCode);
            publishViewModel.Stocks = StockService.GetEntities(b => b.ProCode == prodetailCode);
            publishViewModel.Tags=TagService.GetEntities(c => c.Products.First().Code== prodetailCode);
            return View(publishViewModel);
        
        }
    }
}

WeShop.WeXin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeShop.IService;
using WeShop.WeXin.Models;

namespace WeShop.WeXin.Controllers
{
    public class ProductsController : Controller
    {
        public IProductService ProductService { get; set; }
        

        public ActionResult Index(string proCode = "1001")
        {
            PublishViewModel pro = new PublishViewModel();

            pro.Products = ProductService.GetEntities(n => n.Sorts.First().Code == proCode);
            
            return View(pro);
        }
    }
}

WeShop.WeXin/Views/Products/Index.cshtml
@model WeShop.WeXin.Models.PublishViewModel
@{
    ViewBag.Title = "商品列表";
    Layout = "~/Views/_LayoutMaster.cshtml";
}

<body>
<!--ftop开始-->
<div class="ftop">
    <div class="index_search index_search01">
        <a class="back" onClick="javascript:history.back(-1);">
            <img src="/Content/images/icon_03.png">
        </a>
        <div>
            <input type="text" placeholder="请输入您要搜索的产品">
            <input class="dw" onclick="document.location = 'search_list.html'" type="button" value=" ">
        </div>
    </div>
    <div style="clear: both;"></div>
</div>
<!--ftop开始-->
<div class="search_list">
    <p>
        <a class="on">
            <span>综合</span></a><a>
            <span>销量</span></a><a>
            <span>评价</span></a><a>
            <span class="bg">价格</span></a>
    </p>
    <ul>
        @foreach (var product in Model.Products)
        {
            <li>
                <a href="@Url.Action("Index","ProDetail",new {prodetailCode=product.Code})">
                    <img src="@product.ProPhotoes.First().ImgUrl.Split(',')[0]">
                    <div class="search_item">
                        <p>@product.Name</p>
                        <h2>
                            <i>￥</i><b>@product.SellPrice</b><span>月销18252笔</span></h2>
                    </div>
                </a>
            </li>
        }
    </ul>
</div>
 @section Style
{
        <script src="~/Scripts/swiper.min.js" type="text/javascript"></script>
        <script src="~/Scripts/index.js" type="text/javascript"></script>
    }
<script>
    $(".search_list ul li a img").each(function() {
        var w = $(this).width();
        $(this).height(w + "px");
    })

</script>


</body>