WeShop.WeXin/Controllers/CenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Senparc.Weixin.MP.AdvancedAPIs.OAuth;
using WeShop.IService;
using WeShop.WeXin.Models;
using WeShop.WeXin.Filters;

namespace WeShop.WeXin.Controllers
{
    [OAuthFilter]
    public class CenterController : Controller
    {
        public IUserService UserService { get; set; }
        public IProductService ProductService { get; set; }
        // GET: Center
        public ActionResult Index()
        {
            var userinfo = Session["userinfo"] as OAuthUserInfo;
            return View(userinfo);
        }

        public ActionResult Center_Order()
        {
            return View();
        }

        public ActionResult Center_Order_Dfk()
        {
            HomeViewModel homeViewModel = new HomeViewModel();
            homeViewModel.Products = ProductService.GetEntities(n => true);
            return View(homeViewModel);
        }

        public ActionResult Center_Order_Dfh()
        {
            return View();
        }

        public ActionResult Center_Order_Dsh()
        {
            return View();
        }

        public ActionResult Center_Order_Dpj()
        {
            return View();
        }

        public ActionResult Center_Order_Tk()
        {
            return View();
        }
    }
}

WeShop.WeXin/Controllers/PublishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeShop.IService;
using WeShop.WeXin.Models;

namespace WeShop.WeXin.Controllers
{
    public class PublishController : Controller
    {   
        public IProductService ProductService { get; set; }

        public IPublishService PublishService { get; set; }

        public ActionResult Index(string oneCode = "1000")
        {
            PublishViewModel publishViewModel = new PublishViewModel();

            publishViewModel.Sort1 = PublishService.GetEntities(n =>n.UpCode=="A");
            publishViewModel.Sort2 = PublishService.GetEntities(b =>b.UpCode==oneCode);

            return View(publishViewModel);
        }
    }
}

WeShop.WeXin/Controllers/ShoppingCartController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using WeShop.EFModel;
using WeShop.IService;
using WeShop.WeXin.Models;
using Senparc.Weixin.MP.AdvancedAPIs.OAuth;
using Senparc.Weixin.MP.AdvancedAPIs;

namespace WeShop.WeXin.Controllers
{
    public class ShoppingCartController : Controller
    {
        public ICustomerService CustomerService { get; set; }
        public IShoppingCartService ShoppingCartService { get; set; }
        public IProductService ProductService { get; set; }
        // GET: ShopingCart
        public ActionResult Index()
        {
            HomeViewModel homeViewModel = new HomeViewModel();
            int cid = Convert.ToInt32(Session["Id"]);
            homeViewModel.ShoppingCarts = ShoppingCartService.GetEntities(c=>c.CusId==cid);
            return View(homeViewModel);
        }

        public ActionResult Insert(string date)
        {
            ShoppingCart cart = new ShoppingCart();
            string openid = Session["openid"].ToString();
            int num = Convert.ToInt32(Request["num"]);
            string code = Request["codes"].ToString();
            cart.ProCode = code;
            cart.Qty = num;
            cart.CreateTime = DateTime.Now;
            cart.CusId=CustomerService.GetEntities(c=>c.OpenId==openid).First().Id;
            if (ShoppingCartService.GetCount(s=>s.ProCode==code)<1)
            {
                if (ShoppingCartService.Add(cart))
                {
                    return Json(new {code = 200});
                }
                else
                {
                    return Json(new {code = 400});
                }
            }
            else
            {
                int Qty = ShoppingCartService.GetEntities(c => c.ProCode == code).First().Qty;
                cart.Qty = Qty + num;
                if (ShoppingCartService.Add(cart))
                {
                    return Json(new { code = 200 });
                }
                else
                {
                     return Json(new { code = 400 });
                }
               
            }
        }

        public ActionResult Delete()
        {
            string pcode = Request["cod"].ToString();
            int id = Convert.ToInt32(Session["Id"]);
            var cart = ShoppingCartService.GetEntity(p => p.ProCode == pcode && p.CusId == id);
            if (ShoppingCartService.Remove(cart))
            {
                return Json(new {code = 200});
            }
            else
            {
                return Json(new {code = 400});
            }
        }
    }
}

WeShop.WeXin/Views/_LayoutMaster.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">

    <title>@ViewBag.Title</title>
    <link href="~/Content/css/Cbase.css" type="text/css" rel="stylesheet">
    <link href="~/Content/css/index.css" type="text/css" rel="stylesheet">
    <link href="~/Content/css/swiper.min.css" type="text/css" rel="stylesheet">
    @RenderSection("Style", false)
    <script src="~/Scripts/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/base.js" type="text/javascript"></script>
    <script src="~/Scripts/timer.js" type="text/javascript"></script>
    <link href="~/Content/css/center.css" rel="stylesheet" />
</head>

<body>
@RenderBody()

@RenderSection("Script", false)
</body>
</html>

WeShop.WeXin/Views/_LayoutNav.cshtml
@{
    Layout = "_LayoutMaster.cshtml";
}
@section Style
{
    @RenderSection("Style", false)
}
@section Script
{
    @RenderSection("Script", false)
}
@RenderBody()
<!--fixft开始-->
<div class="fixft">
    <a href="@Url.Action("Index","Home")" class="current">
        <span><img src="~/Content/images/navicon_45.png" class="img1"><img src="~/Content/images/navicon_28.png" class="img2"></span>
        <i>首页</i>
    </a>
    <a href="#">
        <a href="@Url.Action("Index","Publish",new {oneCode="1000"})" class="current">
            <span><img src="~/Content/images/navicon_48.png" class="img1"><img src="~/Content/images/navicon_30.png" class="img2"></span>
            <i>分类</i>
        </a>
    <a href="#">
        <a href="@Url.Action("Index","ShoppingCart")" class="current">
            <span><img src="~/Content/images/navicon_50.png" class="img1"><img src="~/Content/images/navicon_32.png" class="img2"><em>12</em></span>
            <i>购物车</i>
        </a>
    <a href="#">
        <a href="@Url.Action("Index","Center")" class="current">
            <span><img src="~/Content/images/navicon_42.png" class="img1"><img src="~/Content/images/navicon_35.png" class="img2"></span>
            <i>我的</i>
        </a>
</div>
<!--fixft结束--> 